from pathlib import Path
r=Path(__file__).resolve().parents[1];d=r/'docs/ac1'
html='''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Infinity Pixel · AC1</title><style>
:root{color-scheme:dark;--ink:#f2e8ce;--muted:#a8bfb1;--jade:#69be9b;--gold:#e7ae58}*{box-sizing:border-box}body{margin:0;background:#0c211f;color:var(--ink);font:16px/1.65 system-ui,sans-serif}header{padding:22px 5vw;border-bottom:1px solid #304a40;display:flex;align-items:center;justify-content:space-between}header img{width:34px;vertical-align:middle;margin-right:12px}a{color:var(--jade)}nav{display:flex;gap:24px}main{max-width:1380px;margin:auto;padding:45px 5vw}h1{font-size:clamp(40px,6vw,78px);line-height:1.04;letter-spacing:-3px;max-width:760px;margin:12px 0 24px}h2{font-size:32px;line-height:1.2;margin:50px 0 16px}h3{font-size:20px;margin:0 0 8px}p{max-width:850px;color:var(--muted)}.eyebrow{color:var(--gold);letter-spacing:2px;font-size:12px;text-transform:uppercase}.hero{width:100%;border-radius:18px;margin:22px 0}.stats{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #304a40;border-radius:14px;overflow:hidden}.stats div{padding:20px;border-right:1px solid #304a40}.stats strong{display:block;color:var(--gold);font-size:30px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.card{background:#14352f;border:1px solid #355349;border-radius:15px;padding:22px}.card img{display:block;width:100%;border-radius:7px;margin-bottom:15px}.wide{grid-column:1/-1}.tag{display:inline-block;font-size:12px;padding:4px 10px;border:1px solid #587963;border-radius:50px;color:var(--jade)}audio{width:100%;margin-top:12px}ul{padding-left:20px;color:var(--muted)}footer{margin-top:60px;padding:25px 0;border-top:1px solid #304a40;color:var(--muted);font-size:13px}.notice{border-left:3px solid var(--gold);padding:8px 22px;background:#203b30;margin:28px 0}@media(max-width:700px){.grid,.stats{grid-template-columns:1fr}nav{gap:10px;font-size:12px}h1{letter-spacing:-1px}.stats div{border-bottom:1px solid #304a40}}
</style></head><body><header><span><img src="../../assets/ui/inity_mark.svg" alt="Marca de pixels do estúdio Inity Pixel"><b>ESTÚDIO INITY PIXEL</b></span><nav><a href="#arte">Arte</a><a href="#jogo">Jogo</a><a href="#audio">Áudio</a><a href="#entrega">Entrega</a></nav></header><main>
<div class="eyebrow">AC1 · Protótipo integrado · 30 setembro 2026</div><h1>Infinity Pixel</h1><p>Domestique. Posicione. Defenda. Uma clareira, um guardião e uma aliança para atravessar a noite.</p><span class="tag">Nome do jogo atualizado · identidade em revisão pelo grupo</span><img class="hero" src="../../assets/ui/keyart.png" alt="Arte de apresentação: guardião e aliado defendem um refúgio em uma floresta fantástica">
<div class="stats"><div><strong>40 × 40 m</strong>Arena implementada</div><div><strong>112 s</strong>Tema musical original</div><div><strong>35</strong>Verificações no macOS</div><div><strong>3 ameaças</strong>Uma noite para defender</div></div>
<div class="notice"><b>Estado da entrega</b><p>Projeto, recursos e evidências produzidos. Playtest humano, audição, funções individuais e aprovação do grupo continuam pendentes. Trello não publicado. O PCK usa a Godot instalada; não é um aplicativo independente.</p></div>
<h2 id="arte">Da direção visual às malhas</h2><p>A arte de apresentação define o clima. As pranchas abaixo mostram as malhas simples efetivamente integradas, com suas fontes editáveis e as diferenças entre estados.</p><div class="grid">'''
for title,file,desc in [('Guardião do refúgio','guardiao','Frente, lateral e costas; túnica, lenço, bolsa, arma e materiais.'),('Selvagem, aliado e variante','dinossauros','Cauda, crista, colar de vínculo e chifres. A domesticação preserva os HP.'),('Clareira do Refúgio','cenario_dia_noite','Dia/noite capturados na engine; base, posto, entrada e corredor livre.'),('Identidade de Infinity Pixel','identidade','Nome do jogo, marca do estúdio, paleta e tipografia aplicados ao protótipo.')]:
 html+=f'<article class="card"><a href="assets/final/{file}.png"><img src="assets/final/{file}.png" alt="{title}" loading="lazy"></a><h3>{title}</h3><p>{desc}</p><a href="assets/final/{file}.svg">Fonte SVG</a> · <a href="assets/final/{file}.png">PNG para o Trello</a></article>'
html+='</div><p><a href="assets/arena_planta.svg">Planta editável da arena</a> · <a href="ASSETS.md">Recursos, fontes e créditos</a></p><h2 id="jogo">O protótipo em execução</h2><p>Capturas reais da Godot. As cenas de teste organizam posições para isolar comportamentos; não representam aprovação de playtest humano.</p><div class="grid">'
for title,file in [('Menu funcional · 1280×720','01_menu_1280'),('Preparação · HUD real','03_dia'),('Canalização · alvo travado','05_domesticacao'),('Noite · defesa do corredor','07_noite'),('Vitória · retorno ao dia','08_vitoria'),('Derrota · reiniciar ou menu','09_derrota')]:
 html+=f'<article class="card"><a href="evidence/{file}.png"><img src="evidence/{file}.png" alt="{title}" loading="lazy"></a><h3>{title}</h3></article>'
html+='</div><p><a href="evidence/02_menu_1920.png">Menu em 1920×1080</a> · <a href="evidence/03_dia_1920.png">HUD em 1920×1080</a> · <a href="TESTES_AC1.md">Resultados e roteiro humano</a></p><h2 id="audio">Passos do Refúgio</h2><p>Composição original sintetizada: introdução, tema, variação, ponte e retorno. Sem samples externos. Análise técnica sem clipping; musicalidade, emenda e equilíbrio aguardam audição humana.</p><div class="grid">'
for title,file,desc in [('Tema principal · 1:52','refugio_principal','Composição de referência, 56 compassos em ré menor.'),('Menu e preparação · 1:52','refugio_calm','Instrumentação mais leve; aplicada no menu e no dia.'),('Combate noturno · 1:52','refugio_combat','Densidade rítmica maior para a fase de defesa.'),('Noite defendida · 0:04','victory','Sinal de vitória derivado do tema.'),('O refúgio caiu · 0:04','defeat','Sinal descendente para encerrar a tentativa.')]:
 html+=f'<article class="card"><h3>{title}</h3><p>{desc}</p><audio controls preload="none" src="../../assets/audio/{file}.wav"></audio></article>'
html+='''</div><h2 id="entrega">Pronto para a revisão do grupo</h2><div class="grid"><article class="card"><h3>Documentação</h3><ul><li><a href="GDD_AC1.md">GDD da versão 0.2</a></li><li><a href="MATRIZ_ENTREGA.md">Matriz dos oito entregáveis</a></li><li><a href="TRELLO_E_ENTREGA.md">Cards prontos para o Trello</a></li><li><a href="SETUP_MCP.md">Configuração e teste real do MCP</a></li><li><a href="TESTES_AC1.md">Testes e pendências humanas</a></li></ul></article><article class="card"><h3>Como abrir</h3><p>Importe project.godot na Godot 4.7.2 e pressione F5. A pasta delivery contém PCK, iniciador local e vídeo AVI com áudio. O ZIP preserva código, fontes de arte/áudio e documentação.</p><p>Templates ausentes impedem o aplicativo independente. Veja <a href="README.md">instruções de execução e exportação</a>.</p></article></div><footer>Inity Pixel · Murilo Cassetti, Heitor Crispim, Pedro Ferreira e Juan Carlos.<br>Funções a confirmar. Recursos produzidos com auxílio de IA; direção final sujeita à aprovação do grupo.<br>Prazo informado: 04/10/2026 às 23:59. Envio do Trello pelo Game Designer.</footer></main><script>document.querySelectorAll('audio').forEach(a=>a.addEventListener('play',()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause()})));</script></body></html>'''
(d/'galeria.html').write_text(html)
print('Galeria atualizada')
